// Generated by `flutterfire configure` (project `sisapedia`, 26 Agustus 2026)
// — android/ios have real values, `web` below is still a placeholder since
// this app doesn't target web. Re-run `flutterfire configure` to regenerate.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions belum dikonfigurasi untuk platform ini. '
          'Jalankan `flutterfire configure` untuk generate ulang file ini.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    appId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    messagingSenderId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    projectId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    storageBucket: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8WKQahXyk9DUAFFjSRV_cXlxy9mS-gFw',
    appId: '1:645788352305:android:73e0c936795b0aed92fa10',
    messagingSenderId: '645788352305',
    projectId: 'sisapedia',
    storageBucket: 'sisapedia.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC63azhrEtx4aT9bxUe9oGXUBgFSvysGlM',
    appId: '1:645788352305:ios:9b09c43c5992e62392fa10',
    messagingSenderId: '645788352305',
    projectId: 'sisapedia',
    storageBucket: 'sisapedia.firebasestorage.app',
    iosBundleId: 'com.sisapedia.sisapedia',
  );
}
